<?php
// $Id$

// Defines!
define('DIMMI_DEFAULT_BLOCKS', 2);

/**
 * Implementation of hook_help()
 */
function dimmi_help($path, $arg) {
  switch ($path) {
    case 'admin/help#dimmi':
      include_once(drupal_get_path('module', 'dimmi') .'/help/dimmi_admin_help.inc');
      return dimmi_settings_help();
  }
}

/**
 * Implementation of hook_menu()
 */
function dimmi_menu() {
  $items = array();
  $items['admin/settings/dimmi'] = array(
    'title' => 'Dimmi Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dimmi_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dimmi.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_block()
 */
function dimmi_block($op = 'list', $delta = 0, $edit = array()) {

  // List blocks on admin screen.
  //
  if ($op == 'list') {
    $blocks = array();
    for ($delta = 0; $delta < variable_get('dimmi_blocks', DIMMI_DEFAULT_BLOCKS); $delta++) {
      $block = dimmi_get_block($delta);
      $blocks[$delta] = array(
        'info' => $block['description'],
        'cache' => BLOCK_CACHE_GLOBAL,
      );
    }
    return $blocks;
  }

  // Show confguration. Set an ID and a widget type on each block.
  //
  if ($op == 'configure') {
    $block = dimmi_get_block($delta);
    $form['dimmi']['description'] = array(
      '#type' => 'textfield',
      '#title' => t('Block description'),
      '#description' => t('A brief description of your block. Used on the <a href="@block-overview-page">block overview page</a>.', array('@block-overview-page' => url('admin/build/block'))),
      '#default_value' => $block['description'],
    );
    $form['dimmi']['id'] = array(
      '#type' => 'textfield',
      '#title' => t('Dimmi ID'),
      '#description' => t('Enter the Dimmi ID for your restaurant. You can obtain an ID at the <a href="@dimmi-website">Dimmi website</a>.', array('@dimmi-website' => url('http://dimmi.com.au/'))),
      '#default_value' => $block['id'],
      '#size' => 6,
      '#maxlength' => 6,
    );
    $form['dimmi']['widget'] = array(
      '#type' => 'select',
      '#title' => t('Widget Type'),
      '#description' => t('Select the widget type that should be provided by this block.'),
      '#options' => array(
        'button' => t('Booking Widget'),
        'widget' => t('Calendar Widget'),
      ),
      '#default_value' => $block['widget'],
    );
    return $form;
  }

  // Save configuration.
  //
  if ($op == 'save') {
    $id = intval($edit['dimmi_id_' . $delta]);
    if ($id > 0) {
      $dimmi = array(
        'description' => $edit['description'],
        'id' => $id,
        'widget' => $edit['widget'],
      );
      variable_set('dimmi_block_' . $delta, $dimmi);
    }
    else {
      drupal_set_message(t('The Dimmi ID must be a positive number.'), 'error');
    }
  }

  // View the block.
  //
  if ($op == 'view') {
    return dimmi_widget($delta);
  }
}

/**
 * Helper to retrieve the block configuration.
 */
function dimmi_get_block($delta) {
  $default = array('description' => t('Dimmi: unconfigured @delta', array('@delta' => $delta)), 'id' => 0, 'widget' => 'button');
  return variable_get('dimmi_block_' . $delta, $default);
}

/**
 * Create a block with the configured widget.
 *
 * @param $delta
 *   An integer indicating which block settings should be used.
 *
 * @return
 *   A block array.
 */
function dimmi_widget($delta) {
  $block = dimmi_get_block($delta);
  if (!empty($block['$id'])) {
    return array(
      'subject' => $block['description'],
      'content' => '<script type="text/javascript" src="http://cms.dimmi.com.au/Widget.js?ID=' . $block['id'] . '&view=' . $block['widget'] . '"></script>',
    );
  }
}
